{% set version = "1.0.10" %}


package:
  name: xcube_geodb
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-geodb/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 409dd735c3298694b60209a2d78595b5af88d8ff9b63571f6ede5648bf6b6761

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - geodb = xcube_geodb.cli.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - geopandas
    - psycopg2
    - requests
    - python-dotenv
    - shapely

test:
  requires:
    - python {{ python_min }}
  imports:
    - xcube_geodb.core.geodb

about:
  summary: xcube geoDB is a geo-spatial database within the xcube ecosystem.
  home: https://github.com/xcube-dev/xcube-geodb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: geodb is a Python package
  doc_url: https://xcube-dev.github.io/xcube-geodb
  dev_url: https://github.com/xcube-dev/xcube-geodb

extra:
  recipe-maintainers:
    - pont-us
    - TonioF
    - forman
    - AliceBalfanz
    - thomasstorm
    - TejasMorbagal
